---
networks:
  mgmt:
    driver: bridge
  # enable_ipv6: false
  # ipam:
  #   config:
  #     - subnet: 10.47.218.0/24
  #       gateway: 10.47.218.1
  #     - subnet: fd:10:47:218::/64
  #       gateway: fd:10:47:218::1
  eth1:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.214.33.0/24
          gateway: 10.214.33.1
        - subnet: fd:10:214:33::/64
          gateway: fd:10:214:33::1
  eth2:
    driver: bridge
  #   enable_ipv6: false
  # ipam:
  #   config:
  #     - subnet: 10.214.34.0/24
  #       gateway: 10.214.34.1
  #     - subnet: fd:10:214:34::/64
  #       gateway: fd:10:214:34::1
  eth3:
    driver: bridge
  eth4:
    driver: bridge
  eth5:
    driver: bridge
  eth6:
    driver: bridge
  eth7:
    driver: bridge
  eth8:
    driver: bridge
  eth9:
    driver: bridge
  eth10:
    driver: bridge
  eth11:
    driver: bridge
  eth12:
    driver: bridge
  eth13:
    driver: bridge
  eth14:
    driver: bridge
  eth15:
    driver: bridge
  eth16:
    driver: bridge
  eth17:
    driver: bridge
  eth18:
    driver: bridge
  eth19:
    driver: bridge
  eth20:
    driver: bridge
  eth21:
    driver: bridge
  eth22:
    driver: bridge
  eth23:
    driver: bridge
  eth24:
    driver: bridge
services:
  eos_honeypot:
    image: ceos:4.36.0.1F
    container_name: eos_honeypot
    privileged: true
    tty: true
    networks:
      # Create 24 interfaces and map each interface to a different network.
      # Specifically we map eth1 to a specific network, for remote connectivity.
      # Otherwise mapping happens in a random order.
      mgmt:
        interface_name: eth0
      eth1:
        interface_name: eth1
      eth2:
        interface_name: eth2
      eth3:
        interface_name: eth3
      eth4:
        interface_name: eth4
      eth5:
        interface_name: eth5
      eth6:
        interface_name: eth6
      eth7:
        interface_name: eth7
      eth8:
        interface_name: eth8
      eth9:
        interface_name: eth9
      eth10:
        interface_name: eth10
      eth11:
        interface_name: eth11
      eth12:
        interface_name: eth12
      eth13:
        interface_name: eth13
      eth14:
        interface_name: eth14
      eth15:
        interface_name: eth15
      eth16:
        interface_name: eth16
      eth17:
        interface_name: eth17
      eth18:
        interface_name: eth18
      eth19:
        interface_name: eth19
      eth20:
        interface_name: eth20
      eth21:
        interface_name: eth21
      eth22:
        interface_name: eth22
      eth23:
        interface_name: eth23
      eth24:
        interface_name: eth24
    ports:
      - "22:22"
      - "23:23"
    volumes:
      - ./init/rc.local:/etc/rc.local:ro
      - ./init/init.sh:/init.sh:ro
      - ./init/base.cfg:/base.cfg:ro
      - ./init/bashrc:/etc/bashrc:ro
      - ./init/VersionModel.py:/usr/lib/python3.9/site-packages/CliPlugin/VersionModel.py:ro
      - eos_logs:/var/log:rw
      - eos_flash:/mnt/flash:rw
    restart: always
    environment:
      - INTFTYPE=eth
      - ETBA=1
      - SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1
      - CEOS=1
      - EOS_PLATFORM=ceoslab
      - container=docker
      - MAPETH0=1
      - MGMT_INTF=eth0
    entrypoint:
      - /sbin/init
      - systemd.setenv=INTFTYPE=eth
      - systemd.setenv=ETBA=1
      - systemd.setenv=SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1
      - systemd.setenv=CEOS=1
      - systemd.setenv=EOS_PLATFORM=ceoslab
      - systemd.setenv=container=docker
      - systemd.setenv=MAPETH0=1
      - systemd.setenv=MGMT_INTF=eth0
  log_copier:
    image: busybox:1.36
    container_name: log_copier
    depends_on:
      - eos_honeypot
    volumes:
      - ./copy_logs.sh:/copy_logs.sh:ro
      - eos_logs:/eos_logs:ro
      - eos_flash:/eos_flash:ro
      - ./logs:/logs:rw
    entrypoint: [ "/copy_logs.sh", "1800" ]
    restart: always
volumes:
  eos_logs:
  eos_flash:
